### ISSUE TITLE
x86_64-pc-windows-gnu target fails to build

### ISSUE THREAD

**Issue by walksanatora** [cross-rs/cross#1593]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I am trying to run `cross build --target x86_64-pc-windows-gnu` which fails with
```
info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
 23.7 MiB /  23.7 MiB (100 %)  17.1 MiB/s in  1s ETA:  0s
info: rolling back changes
error: failed to install component: 'rust-std-x86_64-pc-windows-gnu', detected conflict: 'lib/rustlib/x86_64-pc-windows-gnu/lib/rsbegin.o'
Error: 
   0: couldn't install `std` for x86_64-pc-windows-gnu
   1: `rustup target add x86_64-pc-windows-gnu --toolchain stable-x86_64-unknown-linux-gnu` failed with exit status: 1
```

### What target(s) are you cross-compiling for?

x86_64-pc-windows-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

```sh
cross build --target x86_64-pc-windows-gnu
```

### Additional information / notes

no clue. I also get the same error on my host machine when trying to install that
```[tasklist]
### Tasks
```

**Comment by Emilgardis** [comment]
What does `rustup target add x86_64-pc-windows-gnu --toolchain stable-x86_64-unknown-linux-gnu` say? You probably need to uninstall your `stable-x86_64-unknown-linux-gnu` toolchain and reinstall it

**Comment by walksanatora** [comment]
yeah I had to manually remove files. because rustup had semi-installed the windows-gnu target. but not installed enough for it to be removable via the rustup command
